FROM python:3.12-slim as base
ENV PATH="/opt/venv/bin:$PATH"

# FROM base as deps
# WORKDIR /app
# RUN python -m venv /opt/venv
# COPY requirements_minimal.txt ./
# RUN pip install -r requirements_minimal.txt

FROM base
ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /app
# COPY --from=deps /opt/venv /opt/venv
COPY . ./
EXPOSE 8051
CMD ["python3", "run.py"]